Socket APIs: __WIZCHIP::_IF Union Reference
__WIZCHIP::_IF Union Reference
#include <wizchip_conf.h>
Public Attributes
struct {
uint8_t(* _read_byte)(uint32_t AddrSel)
void(* _write_byte)(uint32_t AddrSel, uint8_t wb)
} BUS
struct {
uint8_t(* _read_byte)(void)
void(* _write_byte)(uint8_t wb)
} SPI
Detailed Description
The set of interface IO callback func.
Definition at line 174 of file wizchip_conf.h.
Member Data Documentation
uint8_t(* __WIZCHIP::_IF::_read_byte)(void)
Definition at line 181 of file wizchip_conf.h.
Referenced by reg_wizchip_bus_cbfunc(), and reg_wizchip_spi_cbfunc().
void(* __WIZCHIP::_IF::_write_byte)(uint8_t wb)
Definition at line 182 of file wizchip_conf.h.
Referenced by reg_wizchip_bus_cbfunc(), and reg_wizchip_spi_cbfunc().
struct { ... } __WIZCHIP::_IF::BUS
For BUS interface IO
Referenced by reg_wizchip_bus_cbfunc().
struct { ... } __WIZCHIP::_IF::SPI
For SPI interface IO
Referenced by reg_wizchip_spi_cbfunc().
The documentation for this union was generated from the following file:
D:/WORK/2.PROJECTs/IPv4/W5500/4.ioLibrary/ioLibrary_BSD_Ethernet_V102/Ethernet/wizchip_conf.h