Socket APIs: D:/WORK/2.PROJECTs/IPv4/W5500/4.ioLibrary/ioLibrary_BSD_Ethernet_V102/Ethernet/wizchip_conf.c File Reference
wizchip_conf.c File Reference
WIZCHIP Config Header File.
#include "wizchip_conf.h"
Functions
void wizchip_cris_enter (void)
Default function to enable interrupt.
void wizchip_cris_exit (void)
Default function to disable interrupt.
void wizchip_cs_select (void)
Default function to select chip.
void wizchip_cs_deselect (void)
Default function to deselect chip.
uint8_t wizchip_bus_readbyte (uint32_t AddrSel)
Default function to read in direct or indirect interface.
void wizchip_bus_writebyte (uint32_t AddrSel, uint8_t wb)
Default function to write in direct or indirect interface.
uint8_t wizchip_spi_readbyte (void)
Default function to read in SPI interface.
void wizchip_spi_writebyte (uint8_t wb)
Default function to write in SPI interface.
void reg_wizchip_cris_cbfunc (void(*cris_en)(void), void(*cris_ex)(void))
Registers call back function for critical section of I/O functions such as WIZCHIP_READ, WIZCHIP_WRITE, WIZCHIP_READ_BUF and WIZCHIP_WRITE_BUF.
void reg_wizchip_cs_cbfunc (void(*cs_sel)(void), void(*cs_desel)(void))
Registers call back function for WIZCHIP select & deselect.
void reg_wizchip_bus_cbfunc (uint8_t(*bus_rb)(uint32_t addr), void(*bus_wb)(uint32_t addr, uint8_t wb))
Registers call back function for bus interface.
void reg_wizchip_spi_cbfunc (uint8_t(*spi_rb)(void), void(*spi_wb)(uint8_t wb))
Registers call back function for SPI interface.
int8_t ctlwizchip (ctlwizchip_type cwtype, void *arg)
Controls to the WIZCHIP.
int8_t ctlnetwork (ctlnetwork_type cntype, void *arg)
Controls to network.
void wizchip_sw_reset (void)
Reset WIZCHIP by softly.
int8_t wizchip_init (uint8_t *txsize, uint8_t *rxsize)
Initializes WIZCHIP with socket buffer size.
void wizchip_clrinterrupt (intr_kind intr)
Clear Interrupt of WIZCHIP.
intr_kind wizchip_getinterrupt (void)
Get Interrupt of WIZCHIP.
void wizchip_setinterruptmask (intr_kind intr)
Mask or Unmask Interrupt of WIZCHIP.
intr_kind wizchip_getinterruptmask (void)
Get Interrupt mask of WIZCHIP.
int8_t wizphy_getphylink (void)
get the link status of phy in WIZCHIP. No use in W5100
int8_t wizphy_getphypmode (void)
get the power mode of PHY in WIZCHIP. No use in W5100
void wizphy_reset (void)
Reset phy. Vailid only in W5500.
void wizphy_setphyconf (wiz_PhyConf *phyconf)
Set the phy information for WIZCHIP without power mode.
void wizphy_getphyconf (wiz_PhyConf *phyconf)
Get phy configuration information.
void wizphy_getphystat (wiz_PhyConf *phyconf)
Get phy status.
int8_t wizphy_setphypmode (uint8_t pmode)
set the power mode of phy inside WIZCHIP. Refer to PHYCFGR in W5500, PHYSTATUS in W5200
void wizchip_setnetinfo (wiz_NetInfo *pnetinfo)
Set the network information for WIZCHIP.
void wizchip_getnetinfo (wiz_NetInfo *pnetinfo)
Get the network information for WIZCHIP.
int8_t wizchip_setnetmode (netmode_type netmode)
Set the network mode such WOL, PPPoE, Ping Block, and etc.
netmode_type wizchip_getnetmode (void)
Get the network mode such WOL, PPPoE, Ping Block, and etc.
void wizchip_settimeout (wiz_NetTimeout *nettime)
Set retry time value(RTR) and retry count(RCR).
void wizchip_gettimeout (wiz_NetTimeout *nettime)
Get retry time value(RTR) and retry count(RCR).
Variables
_WIZCHIP WIZCHIP
Detailed Description
WIZCHIP Config Header File.
Version
1.0.0
Date
2013/10/21
Revision history
<2013/10/21> 1st Release
Author
MidnightCow
Copyright
Copyright (c) 2013, WIZnet Co., LTD. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the <ORGANIZATION> nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file wizchip_conf.c.
Function Documentation
void wizchip_cris_enter (void)
Default function to enable interrupt.
Note
This function help not to access wrong address. If you do not describe this function or register any functions, null function is called.
Definition at line 47 of file wizchip_conf.c.
Referenced by reg_wizchip_cris_cbfunc().
void wizchip_cris_exit (void)
Default function to disable interrupt.
Note
This function help not to access wrong address. If you do not describe this function or register any functions, null function is called.
Definition at line 53 of file wizchip_conf.c.
Referenced by reg_wizchip_cris_cbfunc().
void wizchip_cs_select (void)
Default function to select chip.
Note
This function help not to access wrong address. If you do not describe this function or register any functions, null function is called.
Definition at line 59 of file wizchip_conf.c.
Referenced by reg_wizchip_cs_cbfunc().
void wizchip_cs_deselect (void)
Default function to deselect chip.
Note
This function help not to access wrong address. If you do not describe this function or register any functions, null function is called.
Definition at line 65 of file wizchip_conf.c.
Referenced by reg_wizchip_cs_cbfunc().
uint8_t wizchip_bus_readbyte (uint32_t AddrSel)
Default function to read in direct or indirect interface.
Note
This function help not to access wrong address. If you do not describe this function or register any functions, null function is called.
Definition at line 71 of file wizchip_conf.c.
Referenced by reg_wizchip_bus_cbfunc().
void wizchip_bus_writebyte (uint32_t AddrSel, uint8_t wb)
Default function to write in direct or indirect interface.
Note
This function help not to access wrong address. If you do not describe this function or register any functions, null function is called.
Definition at line 78 of file wizchip_conf.c.
Referenced by reg_wizchip_bus_cbfunc().
uint8_t wizchip_spi_readbyte (void)
Default function to read in SPI interface.
Note
This function help not to access wrong address. If you do not describe this function or register any functions, null function is called.
Definition at line 84 of file wizchip_conf.c.
Referenced by reg_wizchip_spi_cbfunc().
void wizchip_spi_writebyte (uint8_t wb)
Default function to write in SPI interface.
Note
This function help not to access wrong address. If you do not describe this function or register any functions, null function is called.
Definition at line 90 of file wizchip_conf.c.
Referenced by reg_wizchip_spi_cbfunc().
void reg_wizchip_cris_cbfunc (void(*)(void) cris_en, void(*)(void) cris_ex)
Registers call back function for critical section of I/O functions such as WIZCHIP_READ, WIZCHIP_WRITE, WIZCHIP_READ_BUF and WIZCHIP_WRITE_BUF.
Parameters
cris_en : callback function for critical section enter.
cris_ex : callback function for critical section exit.
Todo:
Describe WIZCHIP_CRITICAL_ENTER and WIZCHIP_CRITICAL_EXIT marco or register your functions.
Note
If you do not describe or register, default functions(wizchip_cris_enter & wizchip_cris_exit) is called.
Definition at line 112 of file wizchip_conf.c.
References __WIZCHIP::_CRIS::_enter, __WIZCHIP::_CRIS::_exit, __WIZCHIP::CRIS, wizchip_cris_enter(), and wizchip_cris_exit().
void reg_wizchip_cs_cbfunc (void(*)(void) cs_sel, void(*)(void) cs_desel)
Registers call back function for WIZCHIP select & deselect.
Parameters
cs_sel : callback function for WIZCHIP select
cs_desel : callback fucntion for WIZCHIP deselect
Todo:
Describe wizchip_cs_select and wizchip_cs_deselect function or register your functions.
Note
If you do not describe or register, null function is called.
Definition at line 126 of file wizchip_conf.c.
References __WIZCHIP::_CS::_deselect, __WIZCHIP::_CS::_select, __WIZCHIP::CS, wizchip_cs_deselect(), and wizchip_cs_select().
void reg_wizchip_bus_cbfunc (uint8_t(*)(uint32_t addr) bus_rb, void(*)(uint32_t addr, uint8_t wb) bus_wb)
Registers call back function for bus interface.
Parameters
bus_rb : callback function to read byte data using system bus
bus_wb : callback function to write byte data using system bus
Todo:
Describe wizchip_bus_readbyte and wizchip_bus_writebyte function or register your functions.
Note
If you do not describe or register, null function is called.
Definition at line 140 of file wizchip_conf.c.
References __WIZCHIP::_IF::_read_byte, _WIZCHIP_IO_MODE_BUS_, __WIZCHIP::_IF::_write_byte, __WIZCHIP::_IF::BUS, __WIZCHIP::IF, __WIZCHIP::if_mode, wizchip_bus_readbyte(), and wizchip_bus_writebyte().
void reg_wizchip_spi_cbfunc (uint8_t(*)(void) spi_rb, void(*)(uint8_t wb) spi_wb)
Registers call back function for SPI interface.
Parameters
spi_rb : callback function to read byte usig SPI
spi_wb : callback function to write byte usig SPI
Todo:
Describe wizchip_spi_readbyte and wizchip_spi_writebyte function or register your functions.
Note
If you do not describe or register, null function is called.
Definition at line 156 of file wizchip_conf.c.
References __WIZCHIP::_IF::_read_byte, _WIZCHIP_IO_MODE_SPI_, __WIZCHIP::_IF::_write_byte, __WIZCHIP::IF, __WIZCHIP::if_mode, __WIZCHIP::_IF::SPI, wizchip_spi_readbyte(), and wizchip_spi_writebyte().
int8_t wizphy_getphylink (void)
get the link status of phy in WIZCHIP. No use in W5100
Definition at line 412 of file wizchip_conf.c.
References PHY_LINK_OFF, and PHY_LINK_ON.
Referenced by ctlwizchip().
int8_t wizphy_getphypmode (void)
get the power mode of PHY in WIZCHIP. No use in W5100
Definition at line 433 of file wizchip_conf.c.
References PHY_POWER_DOWN, and PHY_POWER_NORM.
Referenced by ctlwizchip().
void wizphy_reset (void)
Reset phy. Vailid only in W5500.
Definition at line 454 of file wizchip_conf.c.
Referenced by ctlwizchip(), wizphy_setphyconf(), and wizphy_setphypmode().
Variable Documentation
_WIZCHIP WIZCHIP
Initial value:
=
      {
      .id                  = _WIZCHIP_ID_,
      .if_mode             = _WIZCHIP_IO_MODE_,
      .CRIS._enter         = wizchip_cris_enter,
      .CRIS._exit          = wizchip_cris_exit,
      .CS._select          = wizchip_cs_select,
      .CS._deselect        = wizchip_cs_deselect,
      .IF.BUS._read_byte   = wizchip_bus_readbyte,
      .IF.BUS._write_byte  = wizchip_bus_writebyte
      }
\ref _WIZCHIP instance
Definition at line 95 of file wizchip_conf.c.